version: "3.8"

services:
  app:
    build:
      context: .
      args:
        FARM_API_URL: ${FARM_API_URL}
    ports:
      - "8080:8080"
    environment:
      - FARM_API_URL=${FARM_API_URL}
    restart: unless-stopped
